fix: Corrected crypto.randomBytes mock to return proper buffer length
While running the test, I got the following error:
MongoServerError: uuid must be a 16-byte binary field with UUID (4) subtype

In the Jest test, I mocked the `crypto.randomBytes` function so that it always returns a fixed buffer:

jest.mock('crypto', () => ({
 ...jest.requireActual('crypto'),
 randomBytes: jest.fn(() => Buffer.from('mocked_token'))

 However, Buffer.from('mocked_token') returns a buffer of length 13 bytes because the string 'mocked_token' is 13 characters long. MongoDB expects the UUID to be a binary data with a length of 16 bytes and a subtype of 4. Therefore, when the code attempts to generate a UUID, a buffer of insufficient length is used, causing a validation error.